import { expectAssignable } from 'tsd';
import {
  and,
  andAll,
  arrayOf,
  assert,
  define,
  equals,
  equalsBy,
  equalsKey,
  everyArrayValue,
  everyMapEntry,
  everyOwnEnumerableEntry,
  everySetValue,
  everyTupleValue,
  guardIn,
  hasKey,
  hasKeys,
  isArray,
  isArrayBuffer,
  isAsyncIterable,
  isBigInt,
  isBlob,
  isBoolean,
  isDataView,
  isDate,
  isError,
  isFile,
  isFiniteNumber,
  isFunction,
  isInfiniteNumber,
  isInstanceOf,
  isInteger,
  isIterable,
  isMap,
  isNaN,
  isNegative,
  isNil,
  isNull,
  isNumber,
  isNumberPrimitive,
  isObject,
  isPlainObject,
  isPositive,
  isPrimitive,
  isPromiseLike,
  isRegExp,
  isSafeInteger,
  isSet,
  isString,
  isSymbol,
  isTypedArray,
  isUndefined,
  isURL,
  isWeakMap,
  isWeakSet,
  isZero,
  lazy,
  mapOf,
  narrowKeyTo,
  nonEmptyArrayOf,
  nonNull,
  not,
  nullable,
  nullish,
  oneOf,
  oneOfValues,
  optional,
  optionalKey,
  or,
  predicateToRefine,
  recordOf,
  required,
  safeJsonParse,
  safeParse,
  safeParseWith,
  setOf,
  struct,
  toBooleanPredicates,
  tupleOf,
  typedStruct
} from 'is-kit';
import type {
  ChainResult,
  Guard,
  GuardedOf,
  GuardedWithin,
  InferSchema,
  NoExtraKeys,
  OptionalObjectKeys,
  OptionalSchemaField,
  OutOfGuards,
  ParseResult,
  Predicate,
  Primitive,
  Refine,
  RefineChain,
  Refinement,
  RequiredObjectKeys,
  Schema,
  SchemaField,
  StructOptions,
  TypedStructFields,
  TypedStructShape
} from 'is-kit';

// =============================================
// describe: root entrypoint
// =============================================
// it: exports the complete public runtime API
expectAssignable<readonly unknown[]>([
  and,
  andAll,
  arrayOf,
  assert,
  define,
  equals,
  equalsBy,
  equalsKey,
  everyArrayValue,
  everyMapEntry,
  everyOwnEnumerableEntry,
  everySetValue,
  everyTupleValue,
  guardIn,
  hasKey,
  hasKeys,
  isArray,
  isArrayBuffer,
  isAsyncIterable,
  isBigInt,
  isBlob,
  isBoolean,
  isDataView,
  isDate,
  isError,
  isFile,
  isFiniteNumber,
  isFunction,
  isInfiniteNumber,
  isInstanceOf,
  isInteger,
  isIterable,
  isMap,
  isNaN,
  isNegative,
  isNil,
  isNull,
  isNumber,
  isNumberPrimitive,
  isObject,
  isPlainObject,
  isPositive,
  isPrimitive,
  isPromiseLike,
  isRegExp,
  isSafeInteger,
  isSet,
  isString,
  isSymbol,
  isTypedArray,
  isUndefined,
  isURL,
  isWeakMap,
  isWeakSet,
  isZero,
  lazy,
  mapOf,
  narrowKeyTo,
  nonEmptyArrayOf,
  nonNull,
  not,
  nullable,
  nullish,
  oneOf,
  oneOfValues,
  optional,
  optionalKey,
  or,
  predicateToRefine,
  recordOf,
  required,
  safeJsonParse,
  safeParse,
  safeParseWith,
  setOf,
  struct,
  toBooleanPredicates,
  tupleOf,
  typedStruct
]);

// it: exports the complete public type API
type PublicTypeContract = readonly [
  ChainResult<unknown, readonly []>,
  Guard<unknown>,
  GuardedOf<Guard<string>>,
  GuardedWithin<readonly [Guard<string>], unknown>,
  InferSchema<{ readonly value: Predicate<string> }>,
  NoExtraKeys<{ readonly value: string }, { readonly value: string }>,
  OptionalObjectKeys<{ readonly value?: string }>,
  OptionalSchemaField<Predicate<string>>,
  OutOfGuards<readonly [Guard<string>]>,
  ParseResult<string>,
  Predicate<string>,
  Primitive,
  Refine<string, string>,
  RefineChain<string, readonly []>,
  Refinement<string, string>,
  RequiredObjectKeys<{ readonly value: string }>,
  Schema,
  SchemaField,
  StructOptions,
  TypedStructFields<
    { readonly value: string },
    { readonly value: Predicate<string> }
  >,
  TypedStructShape<{ readonly value: string }>
];

declare const publicTypes: PublicTypeContract;
expectAssignable<readonly unknown[]>(publicTypes);
