import Image from 'next/image';

import { CodeBlock } from '@/components/code/code-block';
import {
  GuideArticle,
  GuideCallout,
  GuideHeader,
  GuideList,
  GuideSection
} from '@/components/guides/guide-layout';
import { GuideTable } from '@/components/guides/guide-table';
import { Paragraph } from '@/components/ui/paragraph';
import { TextLink } from '@/components/ui/text-link';
import { GUIDE_PATHS } from '@/constants/guides';
import { API_REFERENCE_PATHS } from '@/lib/api-metadata';
import { createGuideMetadata } from '@/lib/guide-metadata';

export const metadata = createGuideMetadata(GUIDE_PATHS.heyApiTypedStruct);

const generatedType = `// src/client/types.gen.ts
// Generated by Hey API. Do not edit this file.
export type Pet = {
  id?: number;
  name: string;
};`;

const quickAnswer = `import type { Pet } from '@/client/types.gen';
import {
  isNumber,
  isString,
  optionalKey,
  safeParse,
  typedStruct,
} from 'is-kit';

const isPet = typedStruct<Pet>()({
  id: optionalKey(isNumber),
  name: isString,
});

async function readPet(response: Response) {
  const payload: unknown = await response.json();
  const parsed = safeParse(isPet, payload);

  if (!parsed.valid) {
    throw new Error('Invalid Pet response');
  }

  return parsed.value;
}`;

const optionalAndNullable = `import type { PetDetails } from '@/client/types.gen';
import {
  isNumber,
  isString,
  nullable,
  optionalKey,
  typedStruct,
} from 'is-kit';

// Generated shape:
// type PetDetails = {
//   id?: number;
//   nickname: string | null;
//   notes?: string | null;
// };

const isPetDetails = typedStruct<PetDetails>()({
  id: optionalKey(isNumber),
  nickname: nullable(isString),
  notes: optionalKey(nullable(isString)),
});`;

const nestedDefinitions = `import type {
  Owner,
  PetWithOwner,
} from '@/client/types.gen';
import {
  isNumber,
  isString,
  nullable,
  typedStruct,
} from 'is-kit';

const isOwner = typedStruct<Owner>()({
  id: isNumber,
  name: isString,
});

const isPetWithOwner = typedStruct<PetWithOwner>()({
  id: isNumber,
  owner: nullable(isOwner),
});`;

const mutableCollections = `import type { PetWithTags } from '@/client/types.gen';
import {
  arrayOf,
  define,
  isString,
  optionalKey,
  typedStruct,
} from 'is-kit';

// PetWithTags['tags'] is Array<string> | undefined.
const isPetTags = define<NonNullable<PetWithTags['tags']>>(
  arrayOf(isString),
);

const isPetWithTags = typedStruct<PetWithTags>()({
  name: isString,
  tags: optionalKey(isPetTags),
});`;

const exactResponse = `import type { Pet } from '@/client/types.gen';
import {
  isNumber,
  isString,
  optionalKey,
  typedStruct,
} from 'is-kit';

const isExactPet = typedStruct<Pet>()(
  {
    id: optionalKey(isNumber),
    name: isString,
  },
  { exact: true },
);`;

export default function ValidateHeyApiGeneratedTypesGuidePage() {
  return (
    <GuideArticle>
      <GuideHeader
        breadcrumbLabel='Validate Hey API types'
        media={
          <Image
            src='/iskit_guide5.png'
            alt=''
            width={1000}
            height={420}
            sizes='(max-width: 896px) calc(100vw - 2rem), 864px'
            preload
            className='my-4 h-auto w-full rounded-xl border'
          />
        }
        title='How to Validate Hey API Generated Types with typedStruct'
        description='Keep generated TypeScript types as the source of truth while adding small runtime guards at the API boundaries that need them.'
      />

      <GuideSection title='The quick answer'>
        <Paragraph>
          Import the generated type into a file outside the Hey API output
          directory, then pass it to <code>typedStruct&lt;T&gt;()</code>. The
          resulting guard is checked against that generated object shape.
        </Paragraph>
        <CodeBlock code={generatedType} language='ts' />
        <CodeBlock code={quickAnswer} language='ts' />
        <GuideCallout emphasized>
          Keep the generated type and the hand-written runtime check connected.
          When regeneration changes a field, TypeScript makes the guard file
          fail until its validation policy is updated.
        </GuideCallout>
      </GuideSection>

      <GuideSection title='Generated TypeScript is not runtime validation'>
        <Paragraph>
          Hey API&apos;s TypeScript plugin writes interfaces and type aliases to{' '}
          <code>types.gen.ts</code>. Those types are erased when the application
          is built, so they cannot prove that a server, proxy, cache, fixture,
          or persisted payload actually returned the documented shape.
        </Paragraph>
        <Paragraph>
          Hey API can also generate and integrate runtime validators. Validation
          is not enabled by default because it adds runtime work. Use{' '}
          <code>typedStruct</code> when you want a small hand-written guard for
          selected boundaries rather than generated validation across the SDK.
        </Paragraph>
        <Paragraph>
          See Hey API&apos;s official{' '}
          <TextLink
            href='https://heyapi.dev/docs/openapi/typescript/plugins/typescript'
            target='_blank'
            rel='noreferrer'
          >
            TypeScript plugin documentation
          </TextLink>{' '}
          and{' '}
          <TextLink
            href='https://heyapi.dev/docs/openapi/typescript/plugins/sdk#validators'
            target='_blank'
            rel='noreferrer'
          >
            SDK validator configuration
          </TextLink>{' '}
          for the generated alternatives.
        </Paragraph>
      </GuideSection>

      <GuideSection title='Keep guards outside the generated directory'>
        <Paragraph>
          Treat Hey API&apos;s output folder like a dependency. Regeneration may
          replace its contents, so place guards in an application-owned module
          such as <code>src/validation/pet.ts</code> and import only the
          generated types.
        </Paragraph>
        <GuideList>
          <li>
            <code>src/client/types.gen.ts</code> remains generated.
          </li>
          <li>
            <code>src/validation/pet.ts</code> owns the runtime policy.
          </li>
          <li>
            Application code imports the guard instead of editing generated
            output.
          </li>
        </GuideList>
      </GuideSection>

      <GuideSection title='Model optional and nullable fields separately'>
        <Paragraph>
          OpenAPI distinguishes a missing property from a property whose value
          is <code>null</code>. Preserve that distinction in the guard instead
          of treating both cases as one kind of absence.
        </Paragraph>
        <CodeBlock code={optionalAndNullable} language='ts' />
        <GuideTable
          columns={['Generated field', 'Guard field', 'Accepted runtime value']}
          rows={[
            {
              key: 'required',
              cells: [
                <code key='generated'>name: string</code>,
                <code key='guard'>isString</code>,
                'An own string property'
              ]
            },
            {
              key: 'optional',
              cells: [
                <code key='generated'>id?: number</code>,
                <code key='guard'>optionalKey(isNumber)</code>,
                'A missing key or a number'
              ]
            },
            {
              key: 'nullable',
              cells: [
                <code key='generated'>nickname: string | null</code>,
                <code key='guard'>nullable(isString)</code>,
                'A present string or null'
              ]
            },
            {
              key: 'optional-nullable',
              cells: [
                <code key='generated'>notes?: string | null</code>,
                <code key='guard'>optionalKey(nullable(isString))</code>,
                'A missing key, string, or null'
              ]
            }
          ]}
        />
      </GuideSection>

      <GuideSection title='Compose generated definitions'>
        <Paragraph>
          Reusable OpenAPI definitions usually become reusable generated types.
          Build their guards the same way, then compose the smaller guard into
          the response guard.
        </Paragraph>
        <CodeBlock code={nestedDefinitions} language='ts' />
        <Paragraph>
          If <code>Owner</code> changes after regeneration, <code>isOwner</code>{' '}
          becomes the single place that must adopt the new runtime policy.
        </Paragraph>
      </GuideSection>

      <GuideSection title='Match mutable generated array fields'>
        <Paragraph>
          Hey API may represent collection properties as mutable{' '}
          <code>Array&lt;T&gt;</code> types. <code>arrayOf</code> intentionally
          narrows to a readonly array, so wrap the same runtime check with{' '}
          <code>define</code> when the field guard must match a generated
          mutable array type.
        </Paragraph>
        <CodeBlock code={mutableCollections} language='ts' />
        <GuideCallout>
          The wrapper changes the TypeScript contract to match the generated
          field. It does not change the runtime check: the value must still be
          an array and every element must pass <code>isString</code>.
        </GuideCallout>
      </GuideSection>

      <GuideSection title='Let regeneration expose drift'>
        <Paragraph>
          <code>typedStruct</code> requires every required and optional
          string-keyed property from the generated type to appear in the guard
          schema. If the OpenAPI document adds, removes, or changes a field,
          regenerating the client produces a compile-time error in the guard
          instead of silently leaving the runtime check stale.
        </Paragraph>
        <Paragraph>
          Numeric and symbol properties are outside this contract. That is
          normally a natural fit for JSON object models, whose property names
          are strings.
        </Paragraph>
      </GuideSection>

      <GuideSection title='Choose extra-key behavior deliberately'>
        <Paragraph>
          By default, <code>typedStruct</code> validates declared fields and
          allows additional own enumerable string keys. This is often the safer
          response-boundary default because a server can add a field without
          breaking an older client.
        </Paragraph>
        <CodeBlock code={exactResponse} language='ts' />
        <Paragraph>
          Use <code>exact: true</code> only when extra fields are invalid for
          the boundary itself, such as a strict fixture or a signed payload.
        </Paragraph>
      </GuideSection>

      <GuideSection title='typedStruct or a generated validator?'>
        <GuideTable
          columns={['Approach', 'Best fit', 'Tradeoff']}
          rows={[
            {
              key: 'typed-struct',
              cells: [
                <code key='approach'>typedStruct</code>,
                'A few selected boundaries with small boolean guards',
                'You maintain the runtime policy by hand, with compiler-checked field coverage'
              ]
            },
            {
              key: 'hey-api-validator',
              cells: [
                'Hey API validator plugin',
                'Generated request or response validation integrated into the SDK',
                'Adds a validator library and follows its parsing and error model'
              ]
            }
          ]}
        />
        <Paragraph>
          Choose the generated validator path when the OpenAPI document should
          produce runtime schemas automatically or when structured validation
          errors are required. Choose <code>typedStruct</code> when explicit,
          reusable predicates are the better fit for a smaller part of the
          application.
        </Paragraph>
      </GuideSection>

      <GuideSection title='What typedStruct does not do'>
        <GuideList>
          <li>It does not read or interpret an OpenAPI document.</li>
          <li>It does not generate a guard from an erased TypeScript type.</li>
          <li>
            It does not automatically attach validation to Hey API SDK calls.
          </li>
          <li>
            It does not coerce values or return field-level error details.
          </li>
          <li>
            It cannot verify that a custom predicate&apos;s implementation is
            honest.
          </li>
        </GuideList>
      </GuideSection>

      <GuideSection title='Summary' className='border-t pt-8'>
        <GuideList>
          <li>Keep generated files untouched.</li>
          <li>
            Build application-owned guards against generated object types.
          </li>
          <li>
            Use <code>optionalKey</code> and <code>nullable</code> for their
            distinct OpenAPI contracts.
          </li>
          <li>Compose nested generated definitions from smaller guards.</li>
          <li>
            Prefer generated validators when automatic SDK-wide validation is
            the real requirement.
          </li>
        </GuideList>
        <Paragraph>
          Continue with the{' '}
          <TextLink href={API_REFERENCE_PATHS.typedStruct}>
            typedStruct API reference
          </TextLink>
          , the{' '}
          <TextLink href={GUIDE_PATHS.syncTypeGuards}>
            type-guard synchronization guide
          </TextLink>
          , or the{' '}
          <TextLink href={GUIDE_PATHS.validateUnknown}>
            unknown validation guide
          </TextLink>
          .
        </Paragraph>
      </GuideSection>
    </GuideArticle>
  );
}
