name: Test Types

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup project
        uses: ./.github/actions/setup-project
      - name: Run build
        run: mise run build
      - name: Run type tests
        run: mise run test-types
